name: Build and Publish DockerImage

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        with:
          repository: case-study07/manifest
          
      - name: Run Test
        run: ls

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          tags: ${{ github.run_number }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.foo.bar = "cool"' 'config.yml'
